import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Synapse",
  description: "Generated by Mohammad Taha Batoomi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bgBlackHigh">
        {children}
      </body>
    </html>
  );
}
